### PR TITLE
builder: run filters in ufo lib.plist

### PR DESCRIPTION
**Pull request by m4rc1e**
Depends on https://github.com/googlefonts/fontmake/pull/874, https://github.com/googlefonts/ufo2ft/pull/604

Fixes https://github.com/googlefonts/fontmake/issues/872

cc @yanone @anthrotype

### CODE REVIEW

**Comment by anthrotype** [comment]
@yanone it's deliberately not a string, it's the `Ellipsis` object => https://docs.python.org/3.9/library/constants.html#Ellipsis

it's just a placeholder to say something was omitted and will be filled in later in the pipeline.

**Comment by simoncozens** [comment]
I don't think it is in this case. I think it's meant to be the Python equivalent of the command line `--filter='...'` you just added. So it should be a string.

**Comment by simoncozens** [comment]
Ah, OK. Well, Marc's code is right then.

**Comment by anthrotype** [comment]
FYI https://github.com/googlefonts/fontmake/releases/tag/v3.3.0

**Comment by m4rc1e** [comment]
Thanks Cosimo, I'm rerunning the CI now and it's looking good!

**Comment by anthrotype** [comment]
should you not also bump the minimum required fontmake in setup.py? 
https://github.com/googlefonts/gftools/blob/12a0e7f81ead117e2ad89819f0451b5db1cc4e93/setup.py#L95

**Comment by m4rc1e** [comment]
Good catch.

**Pull request merged**
