### PR TITLE
Add Arabic glyph sets

### PR DESCRIPTION
**Pull request by khaledhosny**

### CODE REVIEW

**Comment by davelab6** [comment]
Thanks @khaledhosny! I'd like to ask you to add more of the contextual information that explains why these characters, in these sets, are defined - similar to the documentation provided for the Latin sets.

**Comment by khaledhosny** [comment]
I included a README file, not sure if it covers the information you want.

**Comment by khaledhosny** [comment]
Why was this closed, is it merged now, superseded, or no longer needed?

**Comment by felipesanches** [comment]
it was a mistake, sorry. I will reopen it.

**Pull request closed without merging**
