### PR TITLE
Add .nam file for African Latin Languages set

### PR DESCRIPTION
**Pull request by moyogo**
This adds the GF African Latin languages set, which extends the GF Latin Pro set, covering orthographies and transcriptions for modern languages. These cover African orthographies but also other language orthographies.

### CODE REVIEW

**Comment by davelab6** [comment]
Excellent! Which locales does this cover?

**Comment by chrissimpkins** [comment]
Thanks Denis!

**Comment by m4rc1e** [comment]
This is cool.

I'm curious how you're sourcing which glyphs we need to include?

**Comment by chrissimpkins** [comment]
D/W Dave Crossland and the decision was made to use the name "Google Fonts Global" for this addition

**Comment by davelab6** [comment]
> This is cool.
> 
> I'm curious how you're sourcing which glyphs we need to include?

@moyogo said he's been spending a lot of time looking at national standards body requirements, community definitions of orthographies, etc

**Comment by chrissimpkins** [comment]
GTG for merge?  We would like to reference it in documentation.

**Comment by tphinney** [comment]
I would love to get the details—at the very least, what additional languages are covered by this further-extended character set.

**Comment by tphinney** [comment]
Also, it looks like a chunk of these (19?) are already in GF Latin Plus. Should they be unique?

**Comment by davelab6** [comment]
> Should they be unique?

Yes

**Comment by tphinney** [comment]
Note that this was a quick look, I might have missed something. But here is the list of glyphs that I think are already in GF Latin Plus:

0x018F  Ə LATIN CAPITAL LETTER SCHWA
0x01E0  Ǡ LATIN CAPITAL LETTER A WITH DOT ABOVE AND MACRON
0x01E1  ǡ LATIN SMALL LETTER A WITH DOT ABOVE AND MACRON
0x01E6  Ǧ LATIN CAPITAL LETTER G WITH CARON
0x01E7  ǧ LATIN SMALL LETTER G WITH CARON
0x01EA  Ǫ LATIN CAPITAL LETTER O WITH OGONEK
0x01EB  ǫ LATIN SMALL LETTER O WITH OGONEK
0x0206  Ȇ LATIN CAPITAL LETTER E WITH INVERTED BREVE
0x0207  ȇ LATIN SMALL LETTER E WITH INVERTED BREVE
0x0226  Ȧ LATIN CAPITAL LETTER A WITH DOT ABOVE
0x0227  ȧ LATIN SMALL LETTER A WITH DOT ABOVE
0x02BB  ʻ MODIFIER LETTER TURNED COMMA
0x02BC  ʼ MODIFIER LETTER APOSTROPHE
0x02BE  ʾ MODIFIER LETTER RIGHT HALF RING
0x02BF  ʿ MODIFIER LETTER LEFT HALF RING
0x02CA  ˊ MODIFIER LETTER ACUTE ACCENT
0x02CB  ˋ MODIFIER LETTER GRAVE ACCENT
0x1E9E  ẞ LATIN CAPITAL LETTER SHARP S
0x20AD  ₭ KIP SIGN

**Comment by chrissimpkins** [comment]
Thank you very much Thomas!

@moyogo do you mind having a look at the char set that you included here and updating it so that it does not include code points that are included in the other Latin encodings?  Thank you!

**Comment by davelab6** [comment]
@moyogo 

>> extends the GF Latin Pro set

Ah, hmm, Laura Meseguer emailed me to say that, 

> I have a question about the glyph set GF-latin-expert_unique-glyphs.nam, where you have located the Small Caps (.sc). Because of the many added capitals letters at the GF-latin-pro_unique-glyphs.nam set, and the GF-latin-AfricanLatinLanguages#177.nam now the .sc. set seems incomplete. 
>
> I wonder:
>
> 1. if you want to add those
>
> 2. in which set? 
>
> Now we have 350 capitals and 230 Small Caps

Indeed, only the Latin Expert set has the small caps. Therefore, perhaps there should be 2 African Latin glyph sets, African Pro and African Expert, to match the 'base' Latin sets?

**Pull request closed without merging**
