### PR TITLE
Refactor binaries into packages

### PR DESCRIPTION
**Pull request by simoncozens**
This is a big PR. It:

* Moves the build system to setuptools+pyproject.toml, fixing #559.
* Moves all the bin/gftools-* scripts into a modules under a `gftools.scripts` package, and setting them as endpoints installed by setuptools, fixing #390 and probably also fixing #560.
* Refactors *most* of the absl-based scripts to use argparse, fixing #531.
* Deprecates a few scripts (font-diff and space-check) and removes a few obviously broken ones (gftools-cldr, gftools-list-variable-source, gftools-udhr), fixing #9 and #14 and closing #633.
* Moves the tests from Lib/gftools/tests to tests/, since they don't need to be installed on the users' system.
* Updates tests so that they *actually* begin to test some of the scripts' functionality.
* Fixes an issue where the builder tests had to be run separately.

### CODE REVIEW

**Comment by m4rc1e** [comment]
Overall looks good but I have a lot of beef with poetry. What does it bring to the table that pip doesn't?

Installing on my system isn't working due kurbopy which needs cargo. Which package uses kurbopy?

**Comment by simoncozens** [comment]
There's no poetry here.

**Comment by simoncozens** [comment]
kurbopy is now used by collidoscope which is used by fontbakery. And I think there's another problem with collidoscope which now prevents it being used in fontbakery, ugh.

**Comment by m4rc1e** [comment]
Thanks.

Sorry, I thought pyproject.toml was a poetry thing, didn't realise it was established in pep 518.

**Review by m4rc1e — APPROVED** [review]
Thanks Simon. this is great!

**Pull request merged**
