### PR TITLE
gen_push_lists: better filtering

### LINKED ISSUE #642: [gen-push-lists] remove invalid path
Last run I had:
- `ofl/reemkufi/static`
But we just want the font dir, not the sub dir

- `lang`
- `lang/tests`
But we just want `lang/languages/*` and `lang/scripts/*`

See prod and sandbox list at commit:
https://github.com/google/fonts/pull/5662/commits/fe8663ba6450cb76392c3a6c9ab1f100d9ec0ae1

with CI fail:
https://github.com/google/fonts/actions/runs/3594031341/jobs/6051766310

### PR DESCRIPTION
**Pull request by m4rc1e**
It shouldn't remove sc families now.

Screenshot 2023-03-16 at 14 46 47

cc @RosaWagner 

Fixes #642

### CODE REVIEW

**Comment by RosaWagner** [comment]
Yes it works! thanks you!

the only problem remaining is the listing of all modified directories in axis registry and lang, when we just want the textprotos:

```
# Sample texts
lang # https://github.com/google/fonts/pull/5925
lang/Lib/gflanguages # https://github.com/google/fonts/pull/5925
lang/languages/th_Thai.textproto # https://github.com/google/fonts/pull/5925
```

**Comment by m4rc1e** [comment]
@RosaWagner should be fixed now.

**Comment by m4rc1e** [comment]
@RosaWagner mind taking another look?

**Comment by RosaWagner** [comment]
I tested with subtree pull from axis registry and lang, and it successfully filtered everything :) thanks a lot Marc

**Pull request merged**
