### PR TITLE
Added check to PR checklist

### PR DESCRIPTION
**Pull request by yanone**
Since many steps in creating a PR are now automated (labels, issue linking), one might simply forget to add the PR to the traffic jam project board where they will be discovered for review.

### CODE REVIEW

**Comment by yanone** [comment]
@m4rc1e:

The Traffic Jam link failed with:
```
                     [ { 'locations': [{'column': 5, 'line': 3}],                                                   
                        'message': 'Your token has not been granted the required scopes to execute '                
                                   "this query. The 'addProjectV2ItemById' field requires one of "                  
                                   "the following scopes: ['project'], but your token has only "                    
                                   "been granted the: ['admin:enterprise', 'admin:gpg_key', "                       
                                   "'admin:org', 'admin:org_hook', 'admin:public_key', "                            
                                   "'admin:repo_hook', 'delete:packages', 'delete_repo', 'gist', "                  
                                   "'notifications', 'repo', 'user', 'workflow', "                                  
                                   "'write:discussion', 'write:packages'] scopes. Please modify "                   
                                   "your token's scopes at: https://github.com/settings/tokens.",                   
                        'type': 'INSUFFICIENT_SCOPES'}
```

While I appreciate the effort on your end to implement my request, after seeing the user experience of having to add the file manually (even if it worked), I now tend to think we should discard this conduct and just make sure by reminding people (and adding a check to the list) that onboarders add the PR manually.

**Comment by m4rc1e** [comment]
@yanone in https://github.com/settings/tokens, add the following to your PAT:


Screenshot 2024-06-27 at 10 11 19

**Comment by yanone** [comment]
Thank you, that worked

**Comment by m4rc1e** [comment]
I'm going to close this. Tbh, the checklist is starting to feel too long and I think people are ignoring it.

**Pull request closed without merging**
