### PR TITLE
Fix weight class fvar

### PR DESCRIPTION
**Pull request by moontypespace**
As discussed here: https://github.com/googlefonts/gftools/issues/477

### CODE REVIEW

**Comment by m4rc1e** [comment]
Thanks! I don't mind this at all.

Btw, we're planning on merging the tests and fixes into a single repo, https://github.com/simoncozens/fontdoctor (still major wip). This approach stops us from writing code twice and keeps it all in sync.

The ci crashes on mypi (will fix later) but your code passes the fix checks so I'm happy.

**Comment by m4rc1e** [comment]
Before I merge, can you drop all the wws commits please.

**Comment by moontypespace** [comment]
> Before I merge, can you drop all the wws commits please.

I am very sorry, but unfortunately I have no idea how to remove a commit. I have never done that before.

**Comment by moontypespace** [comment]
> Thanks! I don't mind this at all.
> 
> Btw, we're planning on merging the tests and fixes into a single repo, https://github.com/simoncozens/fontdoctor (still major wip). This approach stops us from writing code twice and keeps it all in sync.
> 
> The ci crashes on mypi (will fix later) but your code passes the fix checks so I'm happy.

I don't have access to the mentioned repo fontdoctor :(

**Comment by m4rc1e** [comment]
> I am very sorry, but unfortunately I have no idea how to remove a commit. I have never done that before.

Np. `git rebase -i HEAD~5` will bring up git interactive rebase, https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History

**Comment by m4rc1e** [comment]
I don't mind jumping on a call with you quickly to show you rebasing if you'd like?

**Comment by moontypespace** [comment]
> I don't mind jumping on a call with you quickly to show you rebasing if you'd like?

That would be awesome. Do you have skype?

**Comment by m4rc1e** [comment]
Nope. We use google chat. Email is in my github profile.

**Comment by moontypespace** [comment]
> Nope. We use google chat. Email is in my github profile.

Excuse me very much, but I make it just worth. Can you please make it for me?

**Pull request closed without merging**
