### PR TITLE
add-designer: asciify filenames

### LINKED ISSUE #479: add-designer should use ascii only for png file name
cf https://github.com/google/fonts/issues/4262

### PR DESCRIPTION
**Pull request by m4rc1e**
Fixes #479.

@RosaWagner could you test this for me?

### CODE REVIEW

**Comment by RosaWagner** [comment]
It works on Mirko's case

**Comment by RosaWagner** [comment]
Also just tested "Großäî ÉMEæRÂÖLd ùbœfü" and return "grossaiemeaeraolduboefu", so it looks correct. I think the germand transfor `ü` to `ue`, but I don't think they care about our directory names system.

**Comment by m4rc1e** [comment]
Could you also test using `--img_path` with an accented img filename?

**Comment by RosaWagner** [comment]
image path gets renamed after the dir name

**Comment by m4rc1e** [comment]
Cool. I'm happy with this,

**Pull request merged**
