### PR TITLE
README.md: Fix broken links

### PR DESCRIPTION
**Pull request by laerm0**
No issue for this; just noticed it was a broken link.

### CODE REVIEW

**Comment by m4rc1e** [comment]
Could you squash the commits please and repush.

**Comment by laerm0** [comment]
Hey, how's this look? First time squashing commits.

**Comment by laerm0** [comment]
Should I merge or leave that to one of you two?

**Comment by eliheuer** [comment]
I say merge, but Marc knows more about squashing commits than I do, looks good to me.

**Pull request merged**
