### PR TITLE
packager: get files from archives

### PR DESCRIPTION
**Pull request by m4rc1e**
Thought I'd open this before doing the full implementation since it may be controversial.

The aim of this PR is to allow users to fetch fonts/files from online archives such as Github releases. Imo font binaries should not be stored in repos. It is much nicer to create a tagged release which contains an archive which has the released font files e.g here's Roboto Serif's v1.007 release page:

Screenshot 2022-03-02 at 12 05 00

Users can then get the files from this release by using the `archive` field in the upstream yaml file e.g

```
branch: main
# Download url
archive: https://github.com/googlefonts/roboto-serif/releases/download/v1.007/RobotoSerifFonts-v1.007.zip
files:
# works in the same manner, just specify the dirs e.g
variable/RobotoSerif[wght].ttf: RobotoSerif[wght].ttf
...
```

If folks do want this feature, I'll improve it before asking for a review.

### CODE REVIEW

**Comment by simoncozens** [comment]
I'm planning on moving Noto binaries to being delivered via GitHub Releases rather than a repo full of binary files, so yes, I need this.

**Comment by graphicore** [comment]
I believe I decided against adding this feature when I wrote the packager. We all agree, I believe, that having binaries in the repository is not ideal, but, having them as an attachment of a GitHub release is IMO even worse. One reason is that the releases and their attachments are a specific GitHub feature and hence a vendor lock-in. They are even more detached from the repo-history than binaries in git: an attachment doesn't relate at all to the git commit hash. In an ideal world we would build the fonts directly from the sources and record all dependencies required for a reproducible build, this, in my opinion establishes a pattern that is even worse than the status quo of having binaries in the repo, it is a step in the wrong direction.

**Comment by anthrotype** [comment]
GitHub releases are associated with a tagged commit so they can be traced back to the source state at the given tag. It's true that they are a Github-specific feature, even though an handy one

**Comment by simoncozens** [comment]
Note that the suggestion is to take the release from an arbitrary `archive` URL; in our cases this will be a GitHub release URL, but there is no GitHub lock-in here.

**Comment by graphicore** [comment]
OK, no lock-in for arbitrary URLs, but then even more decoupling between sources and binaries.

**Comment by graphicore** [comment]
> GitHub releases are associated with a tagged commit so they can be traced back to the source state at the given tag. It's true that they are a Github-specific feature, even though an handy one

We should use the tag directly then, and store the commit-hash of that, because tags can also change their target. GitHub release attachments can be anything, there's no relation to the source required at all. Sure they are handy, but I think this is not a good case, especially when we should move closer to building from the source not further away.

**Comment by m4rc1e** [comment]
> GitHub release attachments can be anything, there's no relation to the source required at all.

Same argument could be made for the fonts which are stored in the /fonts dir. There's nothing stopping a designer from running the build chain then hand tweaking. This has happened in the past.

**Comment by m4rc1e** [comment]
I reckon the majority of people who will be using this feature will be users of the Unified Font Repository. This repo uses a github action to build and automatically release the fonts. The font artifacts are attached automatically to the release without any human intervention.

**Comment by graphicore** [comment]
> Same argument could be made for the fonts which are stored in the /fonts dir. There's nothing stopping a designer from running the build chain then hand tweaking. This has happened in the past.

True. There's still a timely hint having it fixed in history (Tags can change).  Ultimately reproducible building from source is the one real thing.

**Comment by simoncozens** [comment]
> Ultimately reproducible building from source is the one real thing.

It's the ideal. If we were purist, we would be onboarding source repos and building them. I think we've already accepted the compromise of onboarding binaries. Whether we get the binaries from a repo or from a URL does not impact on the reproducible building question.

**Comment by graphicore** [comment]
> [...] I think we've already accepted the compromise of onboarding binaries. Whether we get the binaries from a repo or from a URL does not impact on the reproducible building question.

Agreed. What I'm arguing is that allowing arbitrary URLs to zip archives is even worse than what we're doing now. In the case @m4rc1e made, of automated builds from UFR, it doesn't look so bad though. But that's a lot of context that the proposal doesn't cover.

**Comment by graphicore** [comment]
> I'd be happy to restrict this so it only works for github releases archives if that makes you feel more comfortable?

I'm already comfortable with leaving this discussion as a trace.

**Comment by m4rc1e** [comment]
Ok cool. Let me tidy up the implementation.

**Comment by m4rc1e** [comment]
I've tried to add this feature as minimally as possible. 

The url is also added to the METADATA.pb `source.commit` field. Perhaps it would be better to request the METADATA protobuf gets its own archive field since it's not really a commit?

```
+source {
+  repository_url: "https://github.com/googlefonts/roboto-serif"
+  commit: "https://github.com/googlefonts/roboto-serif/releases/download/v1.007/RobotoSerifFonts-v1.007.zip"
+}
```

**Comment by m4rc1e** [comment]
@graphicore I guess we could take a look at this.

**Comment by graphicore** [comment]
Yeah, that's an interesting one. For a GitHub release, one could get the commit hash the tag was pointing to at that moment. I can think of a release based workflow where one would always release from a `latest` tag, but I'm not sure how well that would go with GitHub releases. It's possible to add new fields to a protobuf type without breaking backward compatibility (at least in the format, the consumer may still struggle) so the question is maybe which new fields should be in `source` (a `type` one ...). What purpose does `source` serve? Maybe answering that will help us to decide what fields are required.

**Comment by m4rc1e** [comment]
I've decided to go with adding a new field, #517. If gf eng are ok with this, I'll update this pr.

**Comment by simoncozens** [comment]
What are the expected files / structure of the release file? Does the packager look at all the files in the root, or fonts in fonts/ttf/ or ...? Does it look for any metadata files in the release zip? etc.

**Comment by m4rc1e** [comment]
The packager produces upstream.yaml metadata files. The user has to manually input this information. The file includes `files` field which is a mapping that maps the upstream file path to the google/fonts/ofl dir paths. Here's Alegreya's https://github.com/google/fonts/blob/main/ofl/alegreya/upstream.yaml#L2-L5

We won't do anything differently for archives.

**Comment by simoncozens** [comment]
What's the status of this?

**Comment by m4rc1e** [comment]
I've just merged #517 so we should be good. Lemme just take one last look at this and rebase. Will be around half an hour or so.

**Comment by simoncozens** [comment]
Thanks - no hurry, but I will be hoping to build stuff on top of it sometime soon.

**Pull request merged**
