### PR TITLE
packager: add stroke and classifications fields

### PR DESCRIPTION
**Pull request by m4rc1e**
Still WIP. Need to test whether it can handle multiple classifications properly.

cc @eliheuer

### CODE REVIEW

**Comment by m4rc1e** [comment]
It can handle multiple classifications just fine. @eliheuer feel free to test this.

**Review by eliheuer — APPROVED** [review]
LGTM, I left some comments and made some small changed that I pushed to the new-cats branch already

**Comment by eliheuer** [comment]
Thanks @m4rc1e. I tested this after my PR making some small changes and it all seems to work. I'm going to merge this.

**Comment by m4rc1e** [comment]
Thanks for the fixes.

**Pull request merged**
