### PR TITLE
Fix add-font.py relative path to encodings issue #92

### PR DESCRIPTION
**Pull request by eliheuer**
This PR fixes the relative path to encodings problem that was discussed in issue #92, I have a lengthy [post](https://github.com/googlefonts/gftools/issues/92#issuecomment-451381849) there discussing this solution.

### CODE REVIEW

**Comment by m4rc1e** [comment]
Unfortunately this won't work if a user pip installs gftools.

When I check the `enc_path` when using a pip install of this pr, I get the following path.
`/Users/marcfoley/Desktop/venv/encodings/`

My venv dir doesn't contain the encodings dir.

When I attempt to use the script on an ofl dir. Only the menu subset is returned.

**Comment by anthrotype** [comment]
relying on sys.path like that to get some data directory path is not a good idea. You're making lots a assumption about how that python enviornment is set up.
If those encodings are meant to be used by your script, and available not just when running it from the source checkout but also after installing normally it via pip, I'd recommend that you add it to the `package_data` in setup.py, so they will be installed alogside gftools package. Then from the script you can locate the directory relative to `os.path.dirname(gftools.__file__)`, or use methods from pkg_resurces or pkgutil

**Comment by m4rc1e** [comment]
@eliheuer do you need help with this?

**Comment by m4rc1e** [comment]
I am ok with my commit being included

**Comment by m4rc1e** [comment]
@eliheuer I've updated this pr.

I've done the following:
- Moved `encodings/` to `Lib/gftools/encodings/`
- include `encodings/` in `setup.py.package_data`
- Update `nam_dir` flag in `Lib/gftools/util/googlefonts.py` to load the `package_data` by default
 
Please repull and test it.

This pr won't affect the engineers if they're specifying a nam_dir from the cli either.

**Comment by m4rc1e** [comment]
@eliheuer if you're happy with my changes, you may want to tidyup the last commit a bit (whitespace etc). Do that then squash and force push.

**Comment by m4rc1e** [comment]
Thanks Cosimo! to be on the safe side I added setuptools to the setup.py.

@eli please feel free to review this. If it work for you, merge away.

**Comment by eliheuer** [comment]
Hmm... why is there a CLA issue with e58fa6f ?

**Comment by eliheuer** [comment]
Ok, I tested this and it works for enough to merge. It still needs some help parsing VF file names, but that can be another PR.

**Pull request merged**
