### PR TITLE
extend fix_fs_selection with wws bit fix

### PR DESCRIPTION
**Pull request by moontypespace**
Please see: https://github.com/googlefonts/gftools/issues/475

### CODE REVIEW

**Comment by m4rc1e** [comment]
If we do eventually accept families with differing widths, we'll reopen this.

**Comment by moontypespace** [comment]
> Thank you for your PR.
> 
> Our fonts do not conform to the WWS model since we release styles which don't have a normal width as new families, https://fonts.google.com/?query=condensed, hence why we don't set this bit.

@m4rc1e Maybe there is a misunderstanding. But as far as I understand the situation your example of 'Roboto Condensed' fits to WWS (Weight/Width/Slope): 'Roboto Condensed Bold Italic' -> weight= Bold, width=Condensed, slope=Italic.

Do I overlook something?

**Comment by m4rc1e** [comment]
On fonts.google.com, we release Roboto and Roboto Condensed as seperate families.

Roboto

```XML
<namerecord nameID="1" platformID="3" platEncID="1" langID="0x409">
      Roboto
    </namerecord>
```

Roboto Condensed
```XML
    <namerecord nameID="1" platformID="3" platEncID="1" langID="0x409">
      Roboto Condensed
    </namerecord>
```

**Comment by moontypespace** [comment]
Agree @m4rc1e : 
Roboto Normal width name ID 16 = 'Roboto'
Roboto Condensed width name ID 16 = 'Roboto Consensed'

No name ID 21 and 22 in all fonts.

So, my understanding is, that in that case the wws bit should be set (if OS/2 table version 4 is used).

The Micosoft page also says:
_Thus, if a font has a version 4 or later OS/2 table, bit 8 should be set if and only if 'name' entries for IDs 16 and 17 are consistent with the WWS model and entries for IDs 21 and 22 are not included. Conversely, if bit 8 is not set, that will be interpreted to mean that the names provided by IDs 16 and 17 are not consistent with the WWS model and that 'name' entries for IDs 21 and 22 are included._

https://docs.microsoft.com/en-us/typography/opentype/spec/os2#:~:text=Thus%2C%20if%20a,22%20are%20included.

**Pull request closed without merging**
