### PR TITLE
gftools packager: refactor

### PR DESCRIPTION
**Pull request by m4rc1e**
Following PR refactors the packager to meet the following criteria:

- Drop upstream.yaml files since metadata files now have all the necessary source fields
- Simplify the commands based on feedback received from users
- Aggressively simplify. Users weren't too fussed by interactive mode so this has been dropped
- Add a batch packager so we can update all families in the collection
- Simplify code. Codebase is now a quarter of the size and far easier to understand
- Add onboarder checklist to pull request messages
- Don't onboard families that lack family categorisation tags.

### CODE REVIEW

**Comment by simoncozens** [comment]
Somehow this rewrote my repository_url to `https://wwwhub.com/....`...

**Comment by simoncozens** [comment]
Hahaha!

```
    metadata.source.repository_url = metadata.source.repository_url.replace(".git", "")
```

**Comment by m4rc1e** [comment]
@simoncozens I'm very happy with your new commits. Happy to merge if you're happy?

**Comment by simoncozens** [comment]
Yes, LGTM.

**Pull request merged**
