### PR TITLE
Update README to include installation notes for Cairo, Harfbuzz and FreeType

### LINKED ISSUE #106: macOS install requires cairo + pkg-config dependencies (from fontdiffenator --> pycairo)
#### System:

- macOS 10.14.2
- XCode 10.1
- Python 3.7.2

#### What I did:

Attempted a new install of gftools master branch at https://github.com/googlefonts/gftools/commit/8ffa69cf8ea55dea6f0fbda31ff83c544b102871 by cloning the repository and installing with:

```
pip install -e .
```

#### What happened:

```
Installing collected packages: Werkzeug, itsdangerous, Flask, absl-py, glyphsLib, tabulate, pycairo, uharfbuzz, freetype-py, fontdiffenator, nose, olefile, simplejson, pybrowserstack-screenshots, gfdiffbrowsers, gftools
  Running setup.py install for pycairo ... error
    Complete output from command /usr/local/opt/python/bin/python3.7 -u -c "import setuptools, tokenize;__file__='/private/var/folders/x7/vs8mbwmx1hg1vcb53nlygt0m0000gn/T/pip-install-yjt3s04w/pycairo/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/x7/vs8mbwmx1hg1vcb53nlygt0m0000gn/T/pip-record-dbpg93da/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.14-x86_64-3.7
    creating build/lib.macosx-10.14-x86_64-3.7/cairo
    copying cairo/__init__.py -> build/lib.macosx-10.14-x86_64-3.7/cairo
    copying cairo/__init__.pyi -> build/lib.macosx-10.14-x86_64-3.7/cairo
    copying cairo/py.typed -> build/lib.macosx-10.14-x86_64-3.7/cairo
    running build_ext
    'pkg-config' not found.
    Command ['pkg-config', '--print-errors', '--exists', 'cairo >= 1.13.1']

    ----------------------------------------
Command "/usr/local/opt/python/bin/python3.7 -u -c "import setuptools, tokenize;__file__='/private/var/folders/x7/vs8mbwmx1hg1vcb53nlygt0m0000gn/T/pip-install-yjt3s04w/pycairo/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/x7/vs8mbwmx1hg1vcb53nlygt0m0000gn/T/pip-record-dbpg93da/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/x7/vs8mbwmx1hg1vcb53nlygt0m0000gn/T/pip-install-yjt3s04w/pycairo/
```

#### How I Fixed It:

[PyCairo requires a homebrew install of `cairo` and `pkg-config`](https://pycairo.readthedocs.io/en/latest/getting_started.html).  I've apparently previously installed `cairo`, but not `pkg-config`.

```
$ brew install pkg-config
$ pip install -e .
```

and gftools installed without problems.  Happy to file a README update PR with these instructions if I am not missing something.  I checked and `pkg-config` does not appear to be installed with XCode CL tools.  Seems to require a manual install before the pip install attempt here (and for fontdiffenator alone...).

### PR DESCRIPTION
**Pull request by m4rc1e**
Fixes #106 

@chrissimpkins feel free to make any suggestions.

### CODE REVIEW

**Comment by chrissimpkins** [comment]
`pkg-config` appears to be required for the PyCairo dependency.

```
brew install cairo pkg-config freetype harfbuzz
```

With those installs, the pip install works on my end!

Thanks Marc.

**Comment by thundernixon** [comment]
@irink  and I tried following the recommendation in the readme update (we're setting up a Fira Code-building repo as a learning example), but we're still facing a seemingly similar issue with `pycairo`. She'll paste in the error messages, and we can separate it into a separate issue if it's a separate issue.

**Comment by chrissimpkins** [comment]
@thundernixon if you haven't tried it yet, add `pkg-config` to your brew installs.  If it is the same error this should fix it:

```
brew install cairo pkg-config freetype harfbuzz
```

I don't believe that Marc has this in the PR yet.

**Comment by thundernixon** [comment]
Thanks, @chrissimpkins! We'll try that and update

**Comment by m4rc1e** [comment]
Thanks for all of your suggestions. I've added pkg-config to the installation instructions.

**Pull request merged**
