### PR TITLE
Update push module

### PR DESCRIPTION
**Pull request by m4rc1e**
This PR updates the push module and tidies up the tools which use it.

I've done this refactor because we've moved away from classic project boards in google/fonts and we're now using the latest boards which require graph ql. The previous code was also terrible since the three tools were written during hangouts and we needed them quickly. Now that I understand how all the pieces work, I thought it would be a good idea to lay down some quality.

**TL;DR on how it now works.**

The push module now has two main objects, PushItem and PushItems. PushItem is an item such as a font project, axis registry file, designer profile etc that we hope to push to production. PushItems is a container to hold every PushItem. It can populate itself from the server files or from the new google/fonts traffic jam board. It has methods to write server files and to check if paths are invalid.

@simoncozens would you mind taking a quick look? I think I should probably write how this all works in the module's doc string as well.

### CODE REVIEW

**Comment by simoncozens** [comment]
>  would you mind taking a quick look?

I'm really sorry; I'm in do-not-disturb mode until the end of the month to crank out a font by a deadline. :-/

**Comment by m4rc1e** [comment]
obviously, I'll fix the tests before merging.

**Comment by RosaWagner** [comment]
This time it takes all item into account, but the file path are too long:

```
# New
ofl/kapakana/static # https://github.com/google/fonts/pull/2934
ofl/kapakana/upstream.yaml # https://github.com/google/fonts/pull/2934

# Upgrade
ofl/notosanshk # https://github.com/google/fonts/pull/5531
ofl/notosanskr # https://github.com/google/fonts/pull/5532
ofl/notosansnabataean/upstream.yaml # https://github.com/google/fonts/pull/5320
ofl/notosanspalmyrene/upstream.yaml # https://github.com/google/fonts/pull/5321
ofl/notosanspsalterpahlavi/upstream.yaml # https://github.com/google/fonts/pull/5322
ofl/notosanssamaritan/upstream.yaml # https://github.com/google/fonts/pull/5319
ofl/notosanssc # https://github.com/google/fonts/pull/5533
ofl/notosanssogdian/upstream.yaml # https://github.com/google/fonts/pull/5365
ofl/notosanstc # https://github.com/google/fonts/pull/5534
ofl/notoserifdogra # https://github.com/google/fonts/pull/4837
ofl/notoserifhk # https://github.com/google/fonts/pull/5535
ofl/secularone/upstream.yaml # https://github.com/google/fonts/pull/6335

# Designer profile
catalog/designers/colophonfoundry/bio.html # https://github.com/google/fonts/pull/6331
catalog/designers/colophonfoundry/colophonfoundry.png # https://github.com/google/fonts/pull/6331
catalog/designers/colophonfoundry/info.pb # https://github.com/google/fonts/pull/6331
catalog/designers/hansthiessen/bio.html # https://github.com/google/fonts/pull/6317
catalog/designers/hansthiessen/hansthiessen.png # https://github.com/google/fonts/pull/6317
catalog/designers/hansthiessen/info.pb # https://github.com/google/fonts/pull/6317

```

**Comment by m4rc1e** [comment]
Thanks Rosa! I've updated the module so it should now work.

**Pull request merged**
