### PR TITLE
refactoring to use external `gflanguages` module

### PR DESCRIPTION
**Pull request by felipesanches**
https://github.com/felipesanches/gflanguages
(issue #510)

### CODE REVIEW

**Comment by felipesanches** [comment]
> Thanks for this.
> 
> If we're all happy, we should transfer gflanguages to googlefonts

Yes! Be sure to take a look at https://github.com/googlefonts/gftools/issues/510 where I provide a longer explanation of the rationale behind this pull request. The transfer of gflanguages to googlefonts is also mentioned there.

**Comment by felipesanches** [comment]
> It would also be nice to do this for the axis registry as well.

I agree. And it is worth mentioning here (for the public record) that the same approach was already taken for the glyphset files a while ago: https://github.com/googlefonts/glyphsets/

**Comment by m4rc1e** [comment]
I get the following traceback when trying to use gftools add-font:

```
(venv) Marcs-Air-2:tools marcfoley$ gftools add-font ~/Type/fonts/ofl/abeezee/
Traceback (most recent call last):
  File "/Users/marcfoley/Type/tools/bin/gftools-add-font.py", line 286, in <module>
    app.run(main)
  File "/Users/marcfoley/Type/tools/venv/lib/python3.9/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/Users/marcfoley/Type/tools/venv/lib/python3.9/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "/Users/marcfoley/Type/tools/bin/gftools-add-font.py", line 273, in main
    lang_support.LoadLanguages(os.path.join(FLAGS.lang, 'languages'))
  File "/opt/homebrew/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/posixpath.py", line 76, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Comment by felipesanches** [comment]
@m4rc1e this is ready now for another code-review.

**Comment by m4rc1e** [comment]
I'm still getting the same traceback as above when running `gftools add-font`. Please inspect.

**Comment by felipesanches** [comment]
> I'm still getting the same traceback as above when running `gftools add-font`. Please inspect.

I've made the API more robust:
https://github.com/googlefonts/gflanguages/pull/8

Please `pip install -r requirements.txt` again so that you have the latest `gflanguages==0.4.0`. And then `gftools add-font` will work.

**Review by m4rc1e — APPROVED** [review]
LGTM. Thank you!

**Pull request merged**
